name: Build Release APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK with Logs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Release APK (with full logs)
        run: |
          echo "=== Starting Gradle build with --info and --stacktrace ==="
          ./gradlew assembleRelease --info --stacktrace
          echo "=== APK build completed ==="
          echo "Listing APK files:"
          find app/build/outputs/apk -type f -name "*.apk" -print

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Release-APK
          path: app/build/outputs/apk/release/*.apk
